feat: Add Preact tests
aidenybai/million pull request #358
Opened 2023-05-24 23:00 UTC by tobySolutions

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [] Code changes have been tested against prettier, or there are no code changes
- [] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-05-27 19:49 UTC, aidenybai requested changes

2023-05-27 19:49 UTC, aidenybai commented on test/preact-server.test.tsx
> +describe('react-compiler', () => {
preact-compiler

2023-05-27 19:49 UTC, aidenybai commented on test/preact.test.tsx
> +import { block as createBlock } from '../packages/million';
remove this file

2023-05-28 17:16 UTC, tobySolutions commented on test/preact.test.tsx
> +import { block as createBlock } from '../packages/million';
Done!

2023-05-28 17:16 UTC, tobySolutions commented on test/preact-server.test.tsx
> +describe('react-compiler', () => {
Done!

2023-05-28 17:17 UTC, tobySolutions commented
You can check now @aidenybai. Let me know if there is anything else to fix.

2023-05-29 23:18 UTC, aidenybai approved these changes

2023-05-29 23:20 UTC, merged