added guestbook
aidenybai/million pull request #633
Opened 2023-10-02 08:58 UTC by adhirajkar3103

Added Guestbook components in Kitchen Sink

Status

- [ x] Code changes have been tested against prettier, or there are no code changes
- [ x] I know how to update typings and have done so, or typings don't need updating

- [x ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-10-02 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aidenybai/million?pullRequest=633) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aidenybai/million?pullRequest=633) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aidenybai/million?pullRequest=633) it.</sub>

2023-10-03 05:43 UTC, tobySolutions requested changes
Awesome stuff!! @adhirajkar3103. One tiny thing though; could you try replacing the map with the `<For/>` component?
https://million.dev/docs/for

2023-10-03 06:36 UTC, adhirajkar3103 reviewed
Used For component from million instead of map!

2023-10-04 22:00 UTC, tobySolutions approved these changes
LGTM!

2023-10-04 22:00 UTC, merged