Kitchen Sink: Build A Quiz App
aidenybai/million pull request #636
Opened 2023-10-02 15:38 UTC by arunavabasu-03

**Please describe the changes this PR makes and why it should be merged:**
This PR aims to demonstrate  a quiz app  example using million . 
**Status**
Closes : https://github.com/aidenybai/million/issues/607

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-10-02 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aidenybai/million?pullRequest=636) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aidenybai/million?pullRequest=636) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aidenybai/million?pullRequest=636) it.</sub>

2023-10-02 15:57 UTC, deeola commented on packages/kitchen-sink/src/examples/quiz.tsx
> +
Can we move the styling to a different file please? It helps with the general readabilty.

2023-10-02 18:38 UTC, aidenybai commented
Please run `pnpm run cleanup` @arunavabasu-03

2023-10-03 05:39 UTC, tobySolutions requested changes
Could you maybe try using the `<For/>` component to replace the map you have? @deeola? 
https://million.dev/docs/for

2023-10-03 14:10 UTC, arunavabasu-03 commented
> Could you maybe try using the `<For/>` component to replace the map you have? @deeola? https://million.dev/docs/for

it try to do that but it with radio select it is not working properly so done with **`map`** .

2023-10-03 14:10 UTC, arunavabasu-03 commented
> Please run `pnpm run cleanup` @arunavabasu-03

@aidenybai done cleanup !

2023-10-03 15:41 UTC, arunavabasu-03 commented
> > > Could you maybe try using the `<For/>` component to replace the map you have? @deeola? https://million.dev/docs/for
> > 
> > 
> > it try to do that but it with radio select it is not working properly so done with **`map`** .
> 
> Hmm, can you send a screen recording of this behaviour and your code so we can document it? Then you can revert back to map


code - 
```typescript 
 <For each={questions[currentQuestion].options}>
              {(option, index) => (
                <OptionLabel key={index}>
                  <OptionInput
                    type="radio"
                    value={option}
                    checked={selectedOption === option}
                    onChange={handleOptionChange}
                  />
                  {option}
                </OptionLabel>
              )}
            </For>
```

https://github.com/aidenybai/million/assets/73842340/5031c553-60ee-4213-b836-c6f8687f39e9

2023-10-03 16:55 UTC, tobySolutions commented
> > > > Could you maybe try using the `<For/>` component to replace the map you have? @deeola? https://million.dev/docs/for
> > > 
> > > 
> > > it try to do that but it with radio select it is not working properly so done with **`map`** .
> > 
> > 
> > Hmm, can you send a screen recording of this behaviour and your code so we can document it? Then you can revert back to map
> 
> code -
> 
> ```ts
>  <For each={questions[currentQuestion].options}>
>               {(option, index) => (
>                 <OptionLabel key={index}>
>                   <OptionInput
>                     type="radio"
>                     value={option}
>                     checked={selectedOption === option}
>                     onChange={handleOptionChange}
>                   />
>                   {option}
>                 </OptionLabel>
>               )}
>             </For>
> ```
> 
>  million_for.mp4
Thanks for this

2023-10-03 17:03 UTC, tobySolutions commented
Hey there @arunavabasu-03! This is what I have here:


https://github.com/aidenybai/million/assets/96334363/06ba02e5-3598-48e4-b77c-dbfde82815c6

2023-10-04 04:48 UTC, arunavabasu-03 commented
@tobySolutions I think it is because of your dark mode. Can you disable and check?

2023-10-04 21:54 UTC, tobySolutions commented
Hey there @arunavabasu-03, how are you?? The below should fix your issues, check it out and make your fixes. Thanks!



https://github.com/aidenybai/million/assets/96334363/237a9eac-6dcc-4fcc-aae3-b0dd04020799

2023-10-06 22:52 UTC, tobySolutions commented
Hey there @arunavabasu-03, we already have a quiz app on the sink, but, let's review your PR and get it merged shall we?

2023-10-06 22:53 UTC, tobySolutions approved these changes
LGTM!

2023-10-06 22:56 UTC, tobySolutions commented
I think we still have the same issue. I'm gonna merge this for future reference by the way. I think this might be an issue with styled components.

2023-10-08 12:15 UTC, tobySolutions commented
I'll be closing this for now. I'll need @aidenybai and the rest of the team to look into this though

2023-10-08 12:15 UTC, closed without merging