File Upload and Preview
aidenybai/million pull request #637
Opened 2023-10-02 15:44 UTC by darshbaxi

I have made the file upload and preview app in which users can upload files and preview those files. I developed it using the block of million.js.
![image](https://github.com/aidenybai/million/assets/119887723/6c922d4f-a112-4d83-87ef-42b137e67fc1)
![image](https://github.com/aidenybai/million/assets/119887723/821122a3-95d2-4eb9-83cb-5f1d7a614852)

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-10-02 15:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aidenybai/million?pullRequest=637) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aidenybai/million?pullRequest=637) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aidenybai/million?pullRequest=637) it.</sub>

2023-10-02 15:53 UTC, deeola commented on packages/kitchen-sink/src/examples/file-upload-preview.jsx
> +    console.log(file)
Hey, you left this here😉

2023-10-02 15:53 UTC, deeola commented on packages/kitchen-sink/src/examples/file-upload-preview.jsx
> +      <img src={file} />
can we have an 'alt' too?

2023-10-02 16:27 UTC, darshbaxi commented
@deeola suggested changes made. please review it again:)

2023-10-02 18:40 UTC, aidenybai commented
Please run `pnpm run cleanup`

2023-10-02 19:07 UTC, darshbaxi commented
@aidenybai requirement satisfy to run 'pnpm -w run cleanup' command. please review it again:)

2023-10-03 05:37 UTC, tobySolutions commented
Have you worked on the requested changes @deeola?

2023-10-03 06:07 UTC, darshbaxi commented
@tobySolutions Yes, I made the all requested changes suggested.

2023-10-03 15:11 UTC, tobySolutions requested changes
Can you separate the components? It's not really best practice to nest components. Thank you.

2023-10-03 16:10 UTC, darshbaxi commented
@tobySolutions Required changes made, please review it again:)

2023-10-04 13:19 UTC, darshbaxi commented
@deeola,@tobySolutions I made changes that were suggested by you. please review my PR.

2023-10-04 19:55 UTC, darshbaxi reviewed
@tobySolutions,I made the suggested changes:)

2023-10-04 21:47 UTC, tobySolutions approved these changes
LGTM!

2023-10-04 22:08 UTC, merged