feat: Added Data Converter in Kitchen Sink
aidenybai/million pull request #786
Opened 2023-10-24 09:36 UTC by lalitkumawat1m

**Please describe the changes this PR makes and why it should be merged:**
Added Data Converter in Kitchen Sink

Closes: #764

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-10-25 14:22 UTC, tobySolutions approved these changes
LGTM!! 🙌

2023-10-25 14:23 UTC, tobySolutions requested changes

2023-10-25 14:23 UTC, tobySolutions commented on packages/kitchen-sink/src/examples/data-converter.tsx
> +const DataConverter: React.FC = () => {
Your component doesn't use Million though. Can you maybe check this out?  Use the `block` function from Millon

2023-10-26 05:07 UTC, lalitkumawat1m commented
Hey @tobySolutions, I have added a block function. Could you please check now?

2023-10-30 17:54 UTC, tobySolutions approved these changes
LGTM!

2023-10-30 17:55 UTC, tobySolutions commented
Good work @lalitkumawat1m!

2023-10-30 17:55 UTC, merged