Added lang switcher for Million
aidenybai/million pull request #835
Opened 2023-11-16 13:22 UTC by creative-tutorials

**Please describe the changes this PR makes and why it should be merged:**

- Added [Internationalization (i18n) Routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) to Million documentation

- Translations from English to Chinese have been added.

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

2023-11-16 19:56 UTC, Sidd-underscore commented
can i do french lol

2023-11-16 20:41 UTC, creative-tutorials commented
> can i do french lol

You can ask @aidenybai

2023-11-16 21:06 UTC, alantoa commented on website/pages/docs/internals/_meta.zh-CN.json
> +{
This shouldn't be translated I think.

2023-11-16 21:08 UTC, alantoa commented on website/pages/docs/_meta.zh-CN.json
> +  "block": "堵塞（）",
and here also shouldn't be translated

2023-11-16 21:10 UTC, alantoa commented on website/pages/docs/for.zh-CN.mdx
> +## `as` 道具
## `as` prop

2023-11-16 21:12 UTC, alantoa commented on website/pages/docs/internals/mount.zh-CN.mdx
> +# `山(){:jsx}`
# `mount(){:jsx}`

2023-11-16 21:45 UTC, HerringtonDarkholme commented on website/pages/docs/_meta.zh-CN.json
> +  "internals": "内部结构"
I would suggest using `内部原理` instead of `内部结构`. The former translates to `internal mechanism` and the latter translates to `internal structure`.

2023-11-16 22:21 UTC, HerringtonDarkholme commented on website/pages/docs/index.zh-CN.mdx
> +想象一下 React 组件以原始 JavaScript 的速度运行。
```suggestion
可以把它想成用原生 JavaScript 速度运行的 React 组件。
```

I slightly changed the language order to make it sound more native Chinese.

2023-11-16 22:21 UTC, HerringtonDarkholme commented on website/pages/docs/install.en-US.mdx
> +### Install package
Looks like it is duplicated?

2023-11-16 22:21 UTC, HerringtonDarkholme commented on website/pages/docs/install.zh-CN.mdx
> +### Install package
ditto, duplicate sections.

2023-11-16 22:21 UTC, HerringtonDarkholme commented on website/pages/docs/internals/_meta.zh-CN.json
> +  "mount": "山（）",
```suggestion
  "mount": "mount()",
```

2023-11-16 22:21 UTC, HerringtonDarkholme commented on website/pages/docs/internals/_meta.zh-CN.json
> +  "block": "堵塞（）",
```suggestion
  "block": "block()",
```

2023-11-16 22:21 UTC, HerringtonDarkholme commented on website/pages/docs/internals/block.zh-CN.mdx
> +# `堵塞(){:jsx}`
```suggestion
# `block(){:jsx}`
```

2023-11-16 22:21 UTC, HerringtonDarkholme commented on website/pages/docs/internals/block.zh-CN.mdx
> +##### `props` 是一个具有原始值或 `Block` 值的不可变对象。
```suggestion
##### `props` 是一个不可变对象，其值原始值或 `Block` 。
```

2023-11-16 22:25 UTC, tobySolutions commented
> can i do french lol

Sure thing, go ahead please 😁

2023-11-17 00:03 UTC, tobySolutions commented
Please ensure to sign the CLA @creative-tutorials. Thanks!

2023-11-17 05:03 UTC, zhmushan commented on website/pages/docs/_meta.zh-CN.json
> +    "title": "指导"
I prefer to translate "Guide" as "指南"

2023-11-17 05:40 UTC, zhmushan commented on website/pages/docs/virtualization.zh-CN.mdx
> +Million.js 配合得很好 [TanStack 虚拟](https://tanstack.com/virtual/v3/docs/guide/introduction). TanStack Virtual 是一个无头 UI 实用程序，用于虚拟化 React 中的长元素列表。 您可以一起自动使用虚拟化列表中的块。
```suggestion
Million.js 在 [TanStack Virtual](https://tanstack.com/virtual/v3/docs/guide/introduction)中表现非常出色。TanStack Virtual 是一个用于在 React 中虚拟化长列表元素的无头 UI 实用程序，使用它，您可以自动在虚拟化列表中使用块。
```

2023-11-17 05:47 UTC, zhmushan commented on website/pages/docs/virtualization.zh-CN.mdx
> +虚拟化是一种有效渲染大型项目列表的技术。 它仅呈现用户当前可见的项目，而不是呈现所有项目。 这极大地减少了需要创建和更新的 DOM 节点的数量，从而带来了巨大的性能优势。
```suggestion
虚拟化是一种高效渲染大型项目列表的技术。它仅呈现用户当前可见的项目，而不是呈现所有项目。这极大地减少了需要创建和更新的 DOM 节点的数量，从而带来了巨大的性能优势。
```

2023-11-17 05:53 UTC, zhmushan commented on website/pages/docs/virtualization.zh-CN.mdx
> +以下是使用 TanStack Virtual 和 Million.js 虚拟化 div 中的长列表的简单示例：
```suggestion
以下是一个简单示例，演示如何使用 TanStack Virtual 和 Million.js 虚拟化 div 中的长列表：
```

2023-11-17 06:02 UTC, zhmushan commented on website/pages/docs/typescript.zh-CN.mdx
> +评论](https://stackoverflow.com/questions/37006008/typescript-index-signature-is-missing-in-type/65473225#65473225).
```suggestion
为了符合 TypeScript 团队[官方认可的行为](https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024)，你需要使用 `type` 而不是`interface` 来定义 Props。如果你坚持使用 `interface`，可以按照[这个 Stack Overflow 评论](https://stackoverflow.com/questions/37006008/typescript-index-signature-is-missing-in-type/65473225#65473225)的建议添加 `[key: string]: any`。
```

2023-11-17 06:10 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +您可能会看到它的三个常见原因：
```suggestion
有三个常见的原因可能导致你看到这个错误信息：
```

2023-11-17 06:18 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +2.您可能 **忘记使用编译器。**
```suggestion
2. 您可能 **忘记使用编译器。**
```

2023-11-17 06:23 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +您可能听说过 ["渐进增强,"](https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement) 这个想法是工具根据支持的内容逐步使用功能。 类似地, Million.js 具有“渐进降级”的概念，即如果您使用不支持的功能，它将优雅地降级为默认的 React 渲染。
```suggestion
您可能听说过[“渐进增强”](https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement)的概念，即工具根据支持的内容逐步启用功能。类似地，Million.js 具有“渐进降级”的概念，即如果您使用不支持的功能，它将优雅地降级为默认的 React 渲染。
```

2023-11-17 06:30 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +  本节介绍使用块的惯用模式。它不是错误列表，如果您不遵循这些模式，您的应用程序仍然可以运行。
```suggestion
  本节介绍了常见的 block 的使用模式。但它不是错误列表，如果您不遵循这些模式，您的应用程序仍然可以运行。
```

2023-11-17 06:33 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +### 声明块
```suggestion
### 声明 block
```
My suggestion is to use English to convey the technical emphasis you wish to describe, but in the singular form, as there is no plural concept in Chinese.

2023-11-17 06:35 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +  <strong>[Million.js]</strong> 块需要定义为变量声明。
```suggestion
  <strong>[Million.js]</strong> block 需要被定义为变量。
```

2023-11-17 06:38 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +当您有一个未声明为变量的块时，通常会发生上述情况。这会阻止编译器正确分析该块。
```suggestion
上述情况通常发生在你有一个未声明为变量的 block 时。这会阻止编译器正确分析该块。
```

2023-11-17 06:41 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +  <strong>[Million.js]</strong> 块需要定义为变量声明。
This is a runtime warning. If the warning has not been internationalized, it should not be translated here.

2023-11-17 06:48 UTC, zhmushan commented on website/pages/docs/rules.zh-CN.mdx
> +当你有一个像这样的实际 JSX 组件时，通常会发生上述情况 `<Component />{:jsx}` 传递到 `block(){:jsx}` 函数而不是对组件本身的引用。
```suggestion
上述情况通常发生在你将一个实际的 JSX 组件，如 `<Component />{:jsx}` 传递给 `block(){:jsx}` 函数。正确的做法是传递组件本身的引用。
```
Please be aware that the translation provided here is not a literal translation and has been adapted for clarity and readability.

2023-11-17 08:24 UTC, SukkaW commented on website/pages/docs/_meta.zh-CN.json
> +  "rules": "区块规则",
```suggestion
  "rules": "规则",
```

2023-11-17 08:38 UTC, SukkaW commented on website/pages/docs/index.zh-CN.mdx
> +Million.js 是一个极其快速且轻量级的 `<4kb` 虚拟 DOM, 使 React 速度提高了 [70%](https://krausest.github.io/js-framework-benchmark/current.html)。通过使用经过微调、优化的虚拟 DOM, Million.js 减少了 React 的开销。
```suggestion
Million.js 是一个极其快速且轻量级的 `<4kb` 虚拟 DOM。通过使用经过微调、优化的虚拟 DOM, Million.js 可以提升 React 速度达 [70%](https://krausest.github.io/js-framework-benchmark/current.html)。
```

2023-11-17 08:42 UTC, SukkaW commented on website/pages/docs/rules.zh-CN.mdx
> +  相反，确定性回报。
```suggestion
  条件表达式会降低性能。我们建议使用可被静态分析的返回值。
```

2023-11-17 08:57 UTC, SukkaW requested changes
Thanks for your contribution to the Million.js docs!

Unfortunately, the quality of the Simplified Chinese translation is unacceptable. After all, what's the point of offering machine-translated documentation when readers can conveniently use their browser's built-in automatic translation feature?

I am blocking the PR from being merged for now. Meanwhile, we would greatly appreciate community members providing their valuable reviews and suggestions! With this collaborative effort, we hope to ship a more polished version of the Simplified Chinese version of the docs!

2023-11-17 08:59 UTC, creative-tutorials commented
> Please ensure to sign the CLA @creative-tutorials. Thanks!

Done! Thanks @tobySolutions

2023-11-19 22:03 UTC, tobySolutions commented
> Thanks for your contribution to the Million.js docs!
> 
> Unfortunately, the quality of the Simplified Chinese translation is unacceptable. After all, what's the point of offering machine-translated documentation when viewers can conveniently use their browser's built-in automatic translation feature?
> 
> I am blocking the PR from being merged for now. Meanwhile, we would greatly appreciate community members providing their valuable reviews and suggestions for the current translations! With this collaborative effort, we hope to ship a more polished version of the Simplified Chinese version of the docs!

Awesome! Thanks @SukkaW. Much appreciated.

2023-11-28 11:25 UTC, tobySolutions commented
Any updates regarding this @creative-tutorials?

2023-12-02 05:17 UTC, creative-tutorials commented
> Any updates regarding this @creative-tutorials?

Sorry for the late reply. I think they are still use-case for that translate feature, I've checked popular sites like Nodejs and some interesting ones on Product Hunt, Yes the browser can do this, but not everyone would know how to do that.

2023-12-18 23:18 UTC, closed without merging